### ISSUE TITLE
Better BibTeX extension for Zotero - automating .bib file creation

### ISSUE THREAD

**Issue by petrpajdla** [benmarwick/atom-for-students-writing-markdown#1]
This is a really nice guide Ben! Personally I use one more thing that makes the whole process a bit easier, not sure if you are aware of this and simply did not include it because it is slightly more complex but I think it could be useful...

I use Better BibTeX extension to Zotero, it has quite a lot of useful functions ([https://retorque.re/zotero-better-bibtex/](https://retorque.re/zotero-better-bibtex/)) but I want to mention automatic export here. This creates a .bib file based on one of your collections (or a whole library...) and keeps the local .bib file automatically updated with any changes done in Zotero, thus the step where references are copy pasted by hand is automated.

My workflow is usually as follows: 

- create a new sub-collection (folder) in Zotero with references intended to be used in a given article;
- (with Better BibTeX extension) right click the collection, select Export collection, tick Keep updated, select location for the .bib file;
- and that's it. Change the sub-collection as i write and the .bib file is updated on the go...

The settings for individual connected .bib files can be found under Preferences/Better BibTeX/Automatic export.

**Comment by benmarwick** [comment]
Hi Petr, Thanks so much for your kind note! That is great to know about the Better BibTeX extension, I do use it, but I was not aware that it could do that, very helpful to know. Thank you for sharing the details of your workflow, that is useful. I will give it a try. I'm also very pleased with the new integration of Zotero and RStudio described here: https://www.rstudio.com/blog/rstudio-1-4-preview-citations/
